CodingEvents/Models/Event.cs
namespace CodingEvents.Models
{
    public class Event
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string ContactEmail { get; set; }
        public int Id { get; set; }

        public string Location { get; set; }
        public int Attendees { get; set; }
        public EventCategory Category { get; set; }
        public int CategoryId { get; set; }


        public Event(string name, string description, string contactEmail, string location, int attendees, EventCategory category)
        {
            Name = name;
            Description = description;
            ContactEmail = contactEmail;
            Location = location;
            Attendees = attendees;
            Category = category;
        }

        public Event()

        {
        }


        public override string ToString()
        {
            return Name;
        }


        public override bool Equals(object obj)

        {
            return obj is Event @event &&
                   Id == @event.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

CodingEvents/Controllers/EventsController.cs
using CodingEvents.Data;
using CodingEvents.Models;
using CodingEvents.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CodingEvents.Controllers
{
    public class EventsController : Controller
    {
        private EventDbContext context;

        public EventsController(EventDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {
            //  List<Event> events = new List<Event>(EventData.GetAll());
            List<Event> events = context.Events
                .Include(e => e.Category)
                .ToList();

            return View(events);
        }

       
        public IActionResult Add ()
        {
            List<EventCategory> categories = context.Categories.ToList();
            AddEventViewModel addEventViewModel = new AddEventViewModel(categories);

            return View(addEventViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddEventViewModel addEventViewModel)
        {
            if (ModelState.IsValid)
            {
                EventCategory theCategory = context.Categories.Find(addEventViewModel.CategoryId);
                Event newEvent = new Event
                {

                    Name = addEventViewModel.Name,
                    Description = addEventViewModel.Description,
                    ContactEmail = addEventViewModel.ContactEmail,
                    Location = addEventViewModel.Location,
                    Attendees = addEventViewModel.Attendees,
                    Category = theCategory
                };
                //EventData.Add(newEvent);
                context.Events.Add(newEvent);
                context.SaveChanges();

                return Redirect("/Events");
            }

            return View(addEventViewModel);
        }

        public IActionResult Delete()
        {
            //ViewBag.events = EventData.GetAll();
            ViewBag.events = context.Events.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] eventIds)
        {
            foreach (int eventId in eventIds)
            {
                //EventData.Remove(eventId);
                Event theEvent = context.Events.Find(eventId);
                context.Events.Remove(theEvent);
            }
            context.SaveChanges();

            return Redirect("/Events");
        }

        [HttpPost]
        [Route("/Events/Edit/{eventId}")]
        public IActionResult Edit(int eventId)
        {
            Event editingEvent = context.Events.Find(eventId);  //EventData.GetById(eventId);
            context.Events.Add(editingEvent);
            //ViewBag.eventToEdit = editingEvent;
            //ViewBag.title = "Edit Event" + editingEvent.Name + "(id = " + editingEvent.Id + ")";

            return View();
        }

        [HttpPost]
        [Route("/Events/Edit")]
        public IActionResult SubmitEditEventForm(int eventId, string name, string descripton, string location, double attendees)
        {

            Event editngEvent = context.Events.Find(eventId);
                //EventData.GetById(eventId);
            editngEvent.Name = name;
            editngEvent.Description = descripton;
            editngEvent.Location = location;
            editngEvent.Attendees = attendees;
                
            return Redirect("/Events");
        }

        public IActionResult Detail(int id)
        {
            Event theEvent = context.Events
                .Include(e => e.Category)
                .Single(e => e.Id == id);

            List<EventTag> eventTags = context.EventTags
                .Where(et => et.EventId == id)
                .Include(et => et.Tag)
                .ToList();

            EventDetailViewModel viewModel = new EventDetailViewModel(theEvent, eventTags);
            return View(viewModel);
        }
    }
}

CodingEvents/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using CodingEvents.Data;
using CodingEvents.Models;
using CodingEvents.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace CodingEvents.Controllers
{
    public class TagController : Controller
    {
        private EventDbContext context;

        public TagController(EventDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Tag> tags = context.Tags.ToList();
            return View(tags);
        }

        public IActionResult Add()
        {
            Tag tag = new Tag();
            return View(tag);
        }

        [HttpPost]
        public IActionResult Add(Tag tag)
        {
            if (ModelState.IsValid)
            {
                context.Tags.Add(tag);
                context.SaveChanges();
                return Redirect("/Tag/");
            }
            return View("Add", tag);
        }

        public IActionResult AddEvent(int id)
        {
            Event theEvent = context.Events.Find(id);
            List<Tag> possibleTags = context.Tags.ToList();

            AddEventTagViewModel viewModel = new AddEventTagViewModel(theEvent, possibleTags);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddEvent(AddEventTagViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                int eventId = viewModel.EventId;
                int tagId = viewModel.TagId;

                List<EventTag> existingItems = context.EventTags
                    .Where(et => et.EventId == eventId)
                    .Where(et => et.TagId == tagId)
                    .ToList();
                if (existingItems.Count == 0)
                {
                    EventTag eventTag = new EventTag
                    {
                        EventId = eventId,
                        TagId = tagId
                    };
                    context.EventTags.Add(eventTag);
                    context.SaveChanges();
                }

                return Redirect("/Events/Detail/" + eventId);

            }
            return View(viewModel);
        }
    }
}

CodingEvents/Views/Events/Add.cshtml
@model CodingEvents.ViewModels.AddEventViewModel;


<h1>Add Event</h1>

<form asp-controller="Events" asp-action="Add" method="post">
    <div  class="form-group">
        <label asp-for="Name"></label>
         <input asp-for="Name" />
         <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
    <label asp-for="Description"></label>
        <input asp-for="Description" /> 
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="Model.Categories"></select>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail">Contact Email</label>
        <input asp-for="ContactEmail" />
        <span asp-validation-for="ContactEmail"></span>
    </div>
    <div class="form-group">
        <label asp-for="Location"></label>
        <input asp-for="Location" />
        <span asp-validation-for="Location"></span>
    </div>
    <div class="form-group">
        <label asp-for="Attendees">Number of Attendees</label>
        <input asp-for="Attendees" />
        <span asp-validation-for="Attendees"></span>
    </div>
    <input type="submit" value="Add Event" />
</form>

CodingEvents/Views/Events/Delete.cshtml
@{
}

<h1>Delete Event</h1>

<form method="post">
    @foreach(var evt in ViewBag.events)
    {
       <div class="form-group">
            <label>
                <span>@evt.Name</span>
                <input type="checkbox" name="eventIds" value="@evt.Id" class="form-control">
            </label>
       </div>
    }
    <input type="submit" value="Delete Selected Events" class="btn btn-danger">
</form>

CodingEvents/Views/Events/Detail.cshtml
@model CodingEvents.ViewModels.EventDetailViewModel

<h1>@Model.Name</h1>

<table class="table">
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
    <tr>
        <th>Contact Email</th>
        <td>@Model.ContactEmail</td>
    </tr>
    <tr>
        <th>Category</th>
        <td>@Model.CategoryName</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>@Model.TagText</td>
    </tr>
</table>
<a asp-controller="Tag" asp-action="AddEvent" asp-route-id="@Model.EventId">Add Tag</a>

CodingEvents/Views/Events/Edit.cshtml
<h1>@ViewBag.title</h1>

<form asp-controller="Events" action="Edit" method="post">
    <div>
        <label for="name">Name</label>
        <input name="name" type="text" value="@ViewBag.eventToEdit.Name" />
    </div>
    <div class="form-group">
        <label for="description">Descripton</label>
        <input name="description" type="text" value="@ViewBag.eventToEdit.Descripton"/>
    </div>
    <input type="submit" value="Edit Event" />
   // <input type="hidden" value="@ViewBag.eventToEdit.Id" name="eventId" />
</form>

CodingEvents/Views/Events/Index.cshtml
@using CodingEvents.Models

@model List<CodingEvents.Models.Event>

<h1>Coding Events</h1>

<p>
    <a asp-controller="Events" asp-action="Add">Add Event</a>
</p>

<p>
    <a asp-controller="Events" asp-action="Delete">Delete Event</a>
</p>
<p>
    <a asp-controller="Events" asp-action="Edit">Edit Event</a>
</p>

@if (Model.Count == 0)
{
    <p>No events yet!</p>
}
else
{
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Type
        </th>
        <th>
            Contact Email
        </th>
        <th>
            Location
        </th>
        <th>
            Number of Attendees
        </th>
    </tr>
    @foreach(var evt in Model) 
    {
        <tr>
            <td>@evt.Id</td>
            <td><a asp-controller="Events" asp-action="Detail" asp-route-id="@evt.Id">@evt.Name</a></td>
            <td>@evt.Description</td>
            <td>@evt.Category.Name</td>
            <td>@evt.ContactEmail</td>
            <td>@evt.Location</td>
            <td>@evt.Attendees</td>
           
           
        </tr>
    }
</table>
}